query find($id: Int!){
    Media(id: $id){
        id
        idMal
        title {
            romaji
            english
        }
        coverImage{
            medium
            large
            extraLarge
        }
        description(asHtml:false)
        bannerImage
        genres
    }
}